### ISSUE TITLE
Different Mappings for UPDATE and CREATE

### ISSUE THREAD

**Issue by PatrickGrub** [coolOrangeLabs/powerGateTemplate#10]
The customer has in the UPDATE view some fields read-only and some changable.
The read-only fields like "Weight" shall be automatically transfered from the iProperty/Vault UDP to ERP.
The changeable values from the mask should be transfered to ERP and **not** the mapped iProperty/Vault UDP.

The current configuration file uses for update the same section like for create.

In my project I solved it by introducing two different sections in the config file, see here for the commit https://github.com/coolOrangeProjects/Hauer/commit/dcb7699565a0e51168be6fdee019f6300f50d063

**Comment by christiangessner** [comment]
Fixed by changing the architecture to use PowerShell instead of the XML mapping. This has been introduced to simplify the code.

**Comment by PatrickGrub** [comment]
Fixed in fa7ed8756198572e0d6e2bbce421c91c0bb4addd
