### ISSUE TITLE
When an update of an ERP object is not processed correctly show it to the user

### ISSUE THREAD

**Issue by PatrickGrub** [coolOrangeLabs/powerGateTemplate#105]
## Details

When making an update of an ERP object and the plugin **doesn't** throw an exception and instead returns "204 updated" but the item was not updated then it shows success in the GUI:
+ BomDIalog
+ Inventor
+ Vault

### Solution

I have already fixed this in an existing project.
I have created a wrapper called `Update-ERPObjectWithErrorHandling`
See all changes:
https://github.com/coolOrangeProjects/Aichinger/commit/d802ad94c1dc4f665c1a786a9d5f3ff179d9c966

**Comment by georgschwienbacher** [comment]
@PatrickGrub wie wärs wenn das das Produkt übernehmen würde ?

**Comment by PatrickGrub** [comment]
Aufjedenfall, da gibts bereits ein Ticket: https://support.coolorange.com/helpdesk/tickets/4871

**Comment by JakobBertagnolli** [comment]
https://support.coolorange.com/helpdesk/tickets/4871 ist nicht mehr aufrufbar bitte diesen Link verwenden https://app-eu1.hubspot.com/contacts/25067259/ticket/554111982

**Comment by TollJulian** [comment]
after the 'big rework' of the template, I wasn't able to reproduce the issue anymore. Therefore, I close it
