### ISSUE TITLE
automatedRepoCreation Script enhancement

### ISSUE THREAD

**Issue by lustricker** [coolOrangeLabs/powerGateTemplate#128]
- [x] Projekte im Tab `Projects` von pgTemplate auslesen und im erzeugen Script gleich erzeugen
- [x] Folgende Issues in das jeweilige Project einfügen
  - State: closed
  - Label: Automation
- [x] columns.csv und projects.csv entfernen
  - weil, vom powerGateTemplate die Projekte, columns und cards (issues) ausgelesen werden und im neuen repo genau gleich eingefügt werden sollen
- [x] ReadMe erweitern
- [ ] links in issues automatisch austauschen
- [ ] wiki in powershellExtensions schreiben

**Comment by PatrickGrub** [comment]
> columns.csv und projects.csv erweitern

Was meinst du damit? 
Meiner Meinung nach können wir diese löschen, weil die Konfgiratuion soll von den "Github Projekte" kommen.

**Comment by lustricker** [comment]
stimmt, ja. So hatte ich es auch verstanden. Nur hier falsch aufgeschrieben. danke für die INfo.

**Comment by lustricker** [comment]
@PatrickGrub 
was ist mit labels?

**Comment by PatrickGrub** [comment]
Würde ich derzeit kein Aufwand betreiben. Die Labels kommen von labels.csv oder? Wenn das keine direkte Abhängikeit hat würde ich das belassen.

**Comment by georgschwienbacher** [comment]
@lustricker bei unseren Tests hatten wir gesehen, dass dein Token(=Default Token) auch verwendet wird wenn ich einen Token händisch eingebe. Ich habe gerade gesehen, dass der Token den ich verwendet habe auch von dir stammt. Somit ist dies kein Fehler im Script.
