### ISSUE TITLE
Code restructuring

### ISSUE THREAD

**Issue by christiangessner** [coolOrangeLabs/powerGateTemplate#13]
Commonly used code should be located in the "coolOrange" program data directory, rather than in the VDS structure to avoid redundancy and to have a consistent structure.

See Metso SAP project: https://github.com/coolOrangeProjects/Metso-Minerals/tree/master/Files

**Comment by christiangessner** [comment]
need to be discussed with the team

**Comment by PatrickGrub** [comment]
Discussed and approved.

**Comment by christiangessner** [comment]
@lustricker: the client installer must install the files from 
_powerGateTemplate/Files/powerGate/_ --> _C:\ProgramData\coolOrange\powerGate_

**Comment by lustricker** [comment]
> @lustricker: the client installer must install the files from
> _powerGateTemplate\Files\powerGate_ --> _C:\ProgramData\coolOrange\powerGate_

I have troubles understanding this thread.
This issue, or this comment has allready been done by you, right?
