### ISSUE TITLE
Adapt new template functions to GIthub Wiki

### ISSUE THREAD

**Issue by PatrickGrub** [coolOrangeLabs/powerGateTemplate#131]
The current wiki has a old state: https://github.com/coolOrangeLabs/powerGateTemplate/wiki

It should be updated:
+ [X] [Installation page](https://github.com/coolOrangeLabs/powerGateTemplate/wiki/Client-Installation) 
  + Is missing powerEvents
  + Install paths are wrong
  + Something else?
+ [X] Add a new page and explain how to export, change and import the powerGateCOnfig.xml
+ [X] Add a new page for the PDF job see #57
+ [X] Add a new page for the powerEvents restriction see #56
+ [x] [ERP Serach (vault)](https://github.com/coolOrangeLabs/powerGateTemplate/wiki/Client-Search) and [Inventor search](https://github.com/coolOrangeLabs/powerGateTemplate/wiki/Search-Inventor)
  + Old screenshots, replace with new screenshots
  + Create Mapping tables
  + Link this page in other pages like Inventor/Vault workflow
+ [x] [Vault material workflow ](https://github.com/coolOrangeLabs/powerGateTemplate/wiki/Client-Creation) 
  + Old screenshots, replace with new screenshots of "ERP Item" tab
  + Make Mapping tables more easy/inutive to understand
+ [x] [Inventor material workflow ](https://github.com/coolOrangeLabs/powerGateTemplate/wiki/Creation-Inventor) 
  + Old screenshots, replace with new screenshots of  Inventor mask
  + Create Mapping tables
+ [x] [BOM workflow ](https://github.com/coolOrangeLabs/powerGateTemplate/wiki/Client-BOM) 
  + Old screenshots, replace with new screenshots of  Inventor mask
  + Make Mapping tables more easy
  + Describe also that "Structured" BOm must be enabled (see #53)
  + Describe also that AutoCAD Boms are supported but without Xrefs and if the properties are the same like in Inventor

**Comment by PatrickGrub** [comment]
Only missing followin page to finish: https://github.com/coolOrangeLabs/powerGateTemplate/wiki/BOM-Workflow

**Comment by PatrickGrub** [comment]
I have created lot of new pages and new content now.

I would like to have a feedback until 19.06 from you in order to make the wiki simple, clear and without typos.
After the date, I will give @georgschwienbacher the GO in order to use it for the new powerGate projects.

Reviewers: @georgschwienbacher @lustricker @christiangessner @AlexQua @manfredmalleier 

Write your feedback as comments then we can discuss it together.
Thanks for the cooperation!

**Comment by AlexQua** [comment]
Ich weiß zwar nicht was praktisch Sinnvoll ist für die Entwickler als issue zu haben (mit Ausnahme von 1/2 issues), allerdings konnte ich keine größeren Fehler entdecken. Also von mir aus passt das so weit.
@PatrickGrub

**Comment by georgschwienbacher** [comment]
Passt für mich. 
Finde besonders die relativen links mit `[[Wikiname | irgendeinewikiseite]]` gut, da wir uns so in Zukunft einiges an Arbeit ersparen und nicht ständig die Links ändern müssen

**Comment by PatrickGrub** [comment]
Danke für die paar Rückmeldungen, wie angekündigt schließe ich den issue.
Für spätere Rückmeldung einfach hier nachtragen oder neuen issue.
