### ISSUE TITLE
Adapt Issue numbers in template issues

### ISSUE THREAD

**Issue by georgschwienbacher** [coolOrangeLabs/powerGateTemplate#136]
An issue may have a certain number here in the template repository but this number isn't the same once the new repository is created. Furthermore, are the links not create if only `#Issuenum`er? is used.
Possible solution:  `[#111]({reponame}/issues/111)`

![image](https://user-images.githubusercontent.com/31648966/83276644-3523d900-a1d1-11ea-9f83-c0b670f0111a.png)
-----------
![image](https://user-images.githubusercontent.com/31648966/83276723-58e71f00-a1d1-11ea-88f8-60cdfa49a1d8.png)
Zudem werden die Issue Nummern nicht als Link angezeigt

**Comment by PatrickGrub** [comment]
The new script handles this already.
