### ISSUE TITLE
BOM-Transfer - Delete Rows first before creating

### ISSUE THREAD

**Issue by lustricker** [coolOrangeLabs/powerGateTemplate#137]
In the function: `Transfer-Boms`

The order of the requests should be to delete the rows first and then update and then create new ones.

Because if not in this order, it can happen, that a new row is created with the same keys (position..) as the one which gets deleted afterwards...

**Comment by lustricker** [comment]
I guess this was fixed already(?) @christiangessner

**Comment by christiangessner** [comment]
@lustricker, nein, ich glaube nicht, dass da was geändert wurde.
Aber brauchen wir das überhaupt im Template? Das scheint mir recht projektspezifisch zu sein.
