### ISSUE TITLE
Add Jobs Installer and include powerEvents in Client installer

### ISSUE THREAD

**Issue by PatrickGrub** [coolOrangeLabs/powerGateTemplate#15]
Add Jobs Installer and include powerEvents in Client installer.

Lösung bereits gemacht siehe hier https://github.com/coolOrangeProjects/Hauer/commit/5737371340e08ab333701b08b0d5e69256544d49

**Comment by christiangessner** [comment]
will be fixed with next version

**Comment by PatrickGrub** [comment]
Fixed in fa7ed8756198572e0d6e2bbce421c91c0bb4addd

**Comment by lustricker** [comment]
Why is there a powerGateModules directory in the `powerGatePlugin` dir with the same content as in `Datastandard` dir?

![image](https://user-images.githubusercontent.com/56259521/76630378-333a6a00-6540-11ea-829a-dbbe22e46a62.png)
