### ISSUE TITLE
Conversion of umlauts

### ISSUE THREAD

**Issue by MarkusCool** [coolOrangeLabs/powerGateTemplate#152]
In der powerGateConfiguration.xml will ich die Einheit **Stück** mit aufnehmen, da es diese in meinem deutschen Navision gibt. 
`<Entry Key="STÜCK" Value="Stück" />`
Dann speichere ich die Datei und spiele sie mit „Save powerGate configuration“ zurück.
Wenn ich die Einheit auswählen will erscheint aber **"STÃœCK"** in der Auswahlliste. 
Übertragen wird dann der Default Einheitswert PCS.

Wenn ich die Datei nochmals öffne, steht in der XML:
`<Entry Key="STÃœCK" Value="StÃ¼ck" />`
 
Ich habe herausgefunden, dass die XML immer in UTF-8 geöffnet wird, und die Umlaute dabei in Sonderzeichen umgewandelt werden.
 
Mein Workaround: Nachdem ich die Umlaute eingetragen habe konvertiere ich die Datei nach ANSI.
Dann speichere ich sie und spiele sie mit „Save powerGate configuration“ zurück.
Ist halt umständlich, da ich dies bei jeder Änderung machen muss und nicht vergessen darf.

**Comment by lustricker** [comment]
@MarkusCool This is now fixed in the latest version of the template. The workflow for the client remains the same, he can save the file normally after doing some changes (e.g. as UTF-8). The code takes care of converting the xml to the right encoding...
