### ISSUE TITLE
When creating a new item the value of the Type is not set correctly in Nav

### ISSUE THREAD

**Issue by MarkusCool** [coolOrangeLabs/powerGateTemplate#153]
I select a file in Vault where no item exists in Dynamics Nav and the field 'Type' is pre-selected with 'Service' in the 'ERP Item' tab. When I select the 'Create' button the item will be created in Dynamics Nav but the value of the Type of the item is always 'Inventory'.
It should be the value of what I have selected in the 'ERP Item' tab.

**Comment by christiangessner** [comment]
Fixed in NAV Plugin https://github.com/coolOrangeLabs/powergate-dynamics-nav-sample/releases
