### ISSUE TITLE
Wiki: Enhance Installation Description

### ISSUE THREAD

**Issue by lustricker** [coolOrangeLabs/powerGateTemplate#154]
Extend the wiki pages of the "How to install the customizations" (client setup, job setup and server setup) to contain more detailed information on **where** to install these setups. E.g. "install the jobs setup on the machine, where powerJobs is running".

Moreover give information on how the installer works: "It overrides all older files and leaves newer files unchanged.. To make sure you have the latest setup, uninstall the current" etc.

**Comment by JakobBertagnolli** [comment]
@lustricker 
Done? https://github.com/coolOrangeLabs/powerGateTemplate/wiki/Install-customizations

**Comment by PatrickGrub** [comment]
@JakobBertagnolli 
Can add it also to the wiki sidebar because otherwise, it's hard to navigate to this page.

Also, it looks already completed. So can we close the issue?
