### ISSUE TITLE
Logging causes memory leak

### ISSUE THREAD

**Issue by lustricker** [coolOrangeLabs/powerGateTemplate#158]
The default coolOrange logging from `logging.psm1` causes problems when the logging file becomes big!
Disable logging in productive system or set LogLevel to `OFF`!

**Comment by lustricker** [comment]
"Workaround" applied to template, but will leave this Issue open, so we can discuss how we want to proced with this...

**Comment by lustricker** [comment]
Keep in mind, that sometimes the `Log` function is used to display a messagebox... So if disabling the log make sure that the messageboxes are still shown..

**Comment by PatrickGrub** [comment]
I would highly recommend to replace the custom implementation of us in the Logging.psm1 with a standard Log4net library which already solves issues about to big files and so on.

**Comment by PatrickGrub** [comment]
Added new logging which is async logging #171 and solves all performance issues.
