### ISSUE TITLE
Use minimum GUI for Installer so that User cannot change Path

### ISSUE THREAD

**Issue by PatrickGrub** [coolOrangeLabs/powerGateTemplate#16]
- [x] Use GUI without possibility to change path, but with dialog
- [x] Add Icons to the installed programs

**Comment by christiangessner** [comment]
Jobs installer is minimal, Client installer has a dialog but no need to enter anything but the license agreement, Plugin installer asks for the path:
![image](https://user-images.githubusercontent.com/5640189/76662107-60f1d400-657d-11ea-9aa1-034c70bffd65.png)

**Comment by lustricker** [comment]
Patrick and I discussed and would prefer the normal Installer UI, but without the possibility to change the path.
Like in the client installer you mentioned
> Client installer has a dialog but no need to enter anything but the license agreement

**Comment by christiangessner** [comment]
@lustricker, perfect. I am fine with that!
