### ISSUE TITLE
Update screenshots in issues

### ISSUE THREAD

**Issue by georgschwienbacher** [coolOrangeLabs/powerGateTemplate#160]

**Comment by PatrickGrub** [comment]
What issues do you mean?

**Comment by georgschwienbacher** [comment]
sorry Patrick: 
These issues: https://github.com/coolOrangeLabs/powerGateTemplate/issues?q=Config-Questionnaire

Not sure why I thought updating the screenshots would be necessary. My only guess is that the screenshots no longer match our current template.

**Comment by PatrickGrub** [comment]
Obsolete because we dont use anymore the mentioned issues.
