### ISSUE TITLE
Wiki: Explain how to configure connection-string to powerGateServer

### ISSUE THREAD

**Issue by lustricker** [coolOrangeLabs/powerGateTemplate#162]
The most common problem of customer is, that when they install our customizations on an other environment or when they go-live that they get the error: "Connection to powerGateServer could not be established". 

This has various reasons, e.g. wrong connection string, no firewall exception etc.

In the wiki docuemnt how to configure these things, where the config file is found (e.g. communication.psm1) etc.

Moreover there is a stackoverflow [link](https://stackoverflow.com/c/coolorange/questions/31), where I started to write down possible reasons and how to solve them. Please add or modify this article in order that we have a stable document, which we can pass to the customer. Otherwise it is verrrrry boring to everythime debug these things with the customer. Like: "Did you add the exception to the firewall?? blablabla"

**Comment by JakobBertagnolli** [comment]
@lustricker 
almost done! two TODO's left. 
https://github.com/coolOrangeLabs/powerGateTemplate/wiki/Common-errors

**Comment by PatrickGrub** [comment]
@JakobBertagnolli 
I like this wiki, it will help clients for the troubleshooting. If you can add it also to the wiki sidebar because otherwise its hard to navigate to this page.

Also it looks already completed. So can we close the issue?
