### ISSUE TITLE
Create GitHub use wiki for customers

### ISSUE THREAD

**Issue by AlexQua** [coolOrangeLabs/powerGateTemplate#164]
- [x] Check present wikis
- [x] Update/correct wikis
- [x] Get developer feedback
- [x] Correction of the found issues

**Comment by AlexQua** [comment]
@PatrickGrub

**Comment by AlexQua** [comment]
Document is just a draft at best 90% of it need to be updated

**Comment by AlexQua** [comment]
Offene Fragen:

1.  Soll der Kunde bei issues Labels selber hinzufügen?
2. Wenn der Kunde ein issue erstellt soll er da jemand zuweisen oder macht das Proj Management?
3. Soll der Kunde issues schon in einen gewissen Format erstellen oder soll das erst der Entwickler machen?

Bitte beantworten danke @georgschwienbacher @PatrickGrub

**Comment by PatrickGrub** [comment]
> Soll der Kunde bei issues Labels selber hinzufügen?

Ja

---

> Wenn der Kunde ein issue erstellt soll er da jemand zuweisen oder macht das Proj Management?

Er soll den zuständigen Person zuweisen, bei Unklarheit Project Manager (Georg) und Projekt Entwickler.

---

> Soll der Kunde issues schon in einen gewissen Format erstellen oder soll das erst der Entwickler machen?

Gewisses format nein aber gewissen Content ja. zB bei Defects die klassiker: Reproduzier schritte, welche File/Item, wann, welche Maschine usw


---

> Wird das Projekt archiviert und ein Kunde/Händler im Repo gelassen oder wird das Repo gar nicht erst archiviert?

@georgschwienbacher bitte um Hilfe.

**Comment by georgschwienbacher** [comment]
@AlexQua meiner Meinung nach muss der Kunde beim Erstellen **keine** Labels hinzufügen. Lediglich um die Umsetzung zu genehmigen und um das Issue dann abzunehmen.

**Comment by AlexQua** [comment]
@georgschwienbacher @PatrickGrub 

Bitte überprüft die Dokumente bis Montag und mekrt hier im issue die Mängel an.

PS: Ich habe gesehen, dass es das label "Umsetzung genehmigt" nur in den deutschen Repos existiert und deshalb in der Wiki einfach wörtlich übersetzt da ich mir nicht zu 100% sicher bin, dass ich einfach zu blöd war und es übersehen habe.

[Github Quickstart Guide_new.pdf](https://github.com/coolOrangeLabs/powerGateTemplate/files/5665910/Github.Quickstart.Guide_new.pdf)
[Github Quickstart Guide_new.docx](https://github.com/coolOrangeLabs/powerGateTemplate/files/5665911/Github.Quickstart.Guide_new.docx)

**Comment by PatrickGrub** [comment]
Feedback:
+ Für 1.1 Code änderungen für Händler würde ich fast in einem eigenen Dokument packen oder am Ende, weil das in den seltensten Fällen gebraucht wird und das Dokument größer/komplizierter macht das als Auswirkung hat dass die "normalen" Kunden dann abspringen beim Lesen
+ Für 1.2 Releases würde ich vorschlagen einen Screenshto anzufügen, weil ich hatte erst bei Hauer wieder das Problem dass er das nicht findet weil jetzt ziemlich klein Rechts ist und nicht super intuitiv ist.
+ Für  2.1 würde ich noch Ergänzen dass es möglich ist via Email ein kommentar hinzuzufügen und wichtig dass dort Attachments **nicht** funktionieren, deshalb für Bilder oder Attachments bis zu 100MB (glaube ich) ist es ntowendig direkt auf GIthub zu gehen
  + Interessanter Tipp: Copy&PAste aus einem Microsoft Programm zB Excel oder Word werden die Formatierungen mitgenommen wie Tabellen
+ Ich erkläre immer auch die "WATCH" Funktionalität damit der Kunde weiß wie er die "Email" notifications einstellen kann deshalb würde ich das auch im Dokument mitaufnehmen
+ Ich erkläre immer wo generelle Dokumente und Lizensen hinterlegt werden auf der Wiki deshalb würde ich das auch im Dokument mitaufnehmen

**Comment by AlexQua** [comment]
Zum 1. Punkt: Ich würde da dann einfach den kompletten Code Kapitel ans Ende des Dokuments verlegen, ich finde die paar grundlegende Informationen über dem Code tab sind durch Screeenshots schon ziemlich vereinfacht und können für all nützlich/interessant sein.

Zum letzten Punkt: kann ich kann die beiden Wiki Seiten auch gerne nochmal beschreiben, dachte nur dass das ziemlich intuitiv ist da die Seiten jeweils Lizenzen und Dokumente heißen

**Comment by georgschwienbacher** [comment]
@AlexQua das Dokument passt für mich. Schließe mich dem Patrick mit seinen beiden letzten Punkten an (die Watch Funktion + wo Lizenzen/Dokumente liegen) finde ich sehr wichtig

**Comment by AlexQua** [comment]
Email versendet

**Comment by PatrickGrub** [comment]
Ich habe mir die File angeschaut und der Content passt sehr gut!

@georgschwienbacher von mein aus kannst du jetzt diese Files verwenden um den Kunden beim Projektbeginn zuzusenden.

Ich werde in den Projekten weiterhin darauf achten welche Fragen und Unklarheiten trotz des Dokumentes der Kunde/Händler zu Github hat dann können wir weitere Maßnahmen treffen. Das bitte ich auch das Projekt Team im Auge zu behalten @lustricker @JakobBertagnolli @kieninj 

+ [Github Quickstart Guide_new.docx](https://github.com/coolOrangeLabs/powerGateTemplate/files/5800373/Github.Quickstart.Guide_new.docx)
+ [Github Quickstart Guide_new.pdf](https://github.com/coolOrangeLabs/powerGateTemplate/files/5800374/Github.Quickstart.Guide_new.pdf)
