### ISSUE TITLE
Create script to perform "stress test" for ERP API

### ISSUE THREAD

**Issue by georgschwienbacher** [coolOrangeLabs/powerGateTemplate#172]
In order to understand at the beginning of the project if the performance of the ERP API is good enough to process all request in a reasonable amount of time we need to create a script which is easily customizable/runnable in our "ERP API verification meeting"

This will allow us to discover potential risks (= slow performance API) right from the beginning

The operations to test the performance:
- batch create 100 articles/items in the ERP system
- batch update 100 articles/items in the ERP system
- batch create 10 BOMs with 100 children each
- batch update 100 children of one BOM

**Comment by PatrickGrub** [comment]
The most simple approach is to extend our "Requirments document for the ERP Team" see #97
They need to provide an application or a script to make a stress test which can be executed on demand. FOr instance in the beginning of the project but also during the project constantly to ensure that the stress test is still valid.

If the ERP Team provides such an application we can integrate in our automated tests of [Monitoring-ERP-AP](https://github.com/coolOrangeLabs/powerGateTemplate/wiki/Monitoring-ERP-API).

The requirements of the ERP Team "stress-test" application would be
+ No input of item numbers or similar, the data must be generated automatically
+ This stress test can be executed easily every day without the need to change the source code.

Following tests must be processed:
- batch create 100 articles/items in the ERP system
- batch update 100 articles/items in the ERP system
- batch create 10 BOMs with 100 children each
- batch update 100 children of one BOM


@georgschwienbacher what do you think about this, is this realistic?

**Comment by georgschwienbacher** [comment]
eingeplant für Dienstag 23.03

**Comment by PatrickGrub** [comment]
## Test script here
https://github.com/coolOrangeLabs/powerGateTemplate/blob/18d04ef81e89a40795bc1d44973e2e3ffeadbf47/Files/powerGatePlugin/ErpServices/Powershell_Tests/Plugin-Stress-Tests.ps1

## Video usage

https://user-images.githubusercontent.com/36075173/112633987-53cb1e80-8e3a-11eb-9b28-ca831d70431a.mp4
