### ISSUE TITLE
Update coolOrange wiki links in issues and wiki to point to new website

### ISSUE THREAD

**Issue by georgschwienbacher** [coolOrangeLabs/powerGateTemplate#175]
old links: https://www.coolorange.com/wiki/
new links: https://doc.coolorange.com/doku.php

**Comment by PatrickGrub** [comment]
Wiki, automated issues, readme and Installer/code

**Comment by JakobBertagnolli** [comment]
@georgschwienbacher 
Folgendes ist mir aufgefallen. Wenn ich einen alten Link ausführe, werde ich sofort auf den neuen Link umgeleitet (Beispiel: https://www.coolorange.com/wiki/doku.php?id=powergate:installation)
Wiso müssen wir also die Links austauschen?
Wird sich dieses Verhalten in Zukunft ändern oder wir können den issue schließen?

**Comment by PatrickGrub** [comment]
Wir können den Issue schließen weil das derzeit passt.
