### ISSUE TITLE
Vault process remains open after closing the Vault Client

### ISSUE THREAD

**Issue by manuelcassan** [coolOrangeLabs/powerGateTemplate#179]
The Vault process remains open after closing Vault.
The issue is reproducible using the 2021 version of Autodesk software and the powerGateTemplate (Plugin + Client)

### Steps to reproduce:
1. Install the powerGateTemplate Client + Plugin
2. Start the Vault Client
3. Close the Vault Client
4. Check Task Manager

### Remarks
When removing the [Logging.psm1] or disable the logging initialization (https://github.com/coolOrangeLabs/powerGateTemplate/blob/18d04ef81e89a40795bc1d44973e2e3ffeadbf47/Files/powerGate/Modules/Logging.psm1) the process is closing correctly

**Comment by PatrickGrub** [comment]
This defect is important since the vault process remains open in every project where we use the template.

Estimation unclear: For the first analyze I would say a "B"

as discussed @georgschwienbacher is planning the implementation.

**Comment by manuelcassan** [comment]
Issue is not reproducible anymore after removing the logging initialization from "C:\ProgramData\coolOrange\powerGate\Modules\Logging.psm1":
`# PSFramework Version 1.5.172
<#
$commonModulePath = "C:\ProgramData\coolOrange\powerGate\PSFramework\PSFramework"
Import-Module -Name $commonModulePath -Global -Verbose

$generalLogPath = Join-Path $env:LOCALAPPDATA "coolOrange\Projects\default.log"
Initialize-CoolOrangeLogging -LogPath $generalLogPath`
#>

**Comment by xdumont** [comment]
I try to comment as explain. Yes the process close after I close Vault Explorer but... my tab are empty now (ERP BOM and ERP Item).
Just to know, I'm under release R2022 (I adapt the R2021 template to work with R2022). Without this workarround, the tab are working as expected.

Do you have an updated templates?

**Comment by georgschwienbacher** [comment]
will be analyzed today by @dianarene

**Comment by PatrickGrub** [comment]
I could reproduce it by isolating it only to this line:
+ `Import-Module -Name C:\ProgramData\coolOrange\powerGate\PSFramework\PSFramework-Global -Verbose`

What I tried:
+ To remove the module again to ensure it was clean upright: `Remove-Module -Name "PSFramework" -Force -Verbose`
  + Without success
+ We use PSFramwework Version `1.5.172`, so I installed latest Version `1.6.205` from the Powershell gallery
  + Without success

Next steps:
+ Investiage with process explorer
+ Ask Wolfgang for deeper analyse

**Comment by PatrickGrub** [comment]
## Solution

The solution is to call:
```Powershell
    Wait-PSFMessage
    Get-PSFRunspace | Stop-PSFRunspace
    [PSFramework.PSFCore.PSFCoreHost]::Uninitialize()
```

I have added it to the Logout function of Datastandard in **Vault**.
In **Inventor** it was not necessary because the library itself cleans it up correctly.

PS: I have tried to add this solution to a generic event like on the closure of the powershell runspace but it didn't work:
```PowerShell

# $Host.Runspace is always null in datastandard
Get-Runspace | foreach {
    $job = Register-ObjectEvent -InputObject $_ -EventName "StateChanged" -Action {
        param($RunspaceStateEventArgs)
        if($RunspaceStateEventArgs.State -eq "Closing") {
            
            Remove-CoolOrangeLogging
            Get-EventSubscriber | Unregister-Event 
        }
    }
}
```

**Comment by PatrickGrub** [comment]
@manuelcassan for your information the issue is fixed you can close the support ticket.
