### ISSUE TITLE
BOM entries with position number '0' are deleted

### ISSUE THREAD

**Issue by MarkusCool** [coolOrangeLabs/powerGateTemplate#181]
Das Verhalten ist mit dem Inventor Beispiel „Test Station.iam“ nachvollziehbar.
Wenn ich auf der Baugruppe M178-1000.iam den BOM Transfer anstoße, wird die BOM korrekt an NAV übergeben.
Es gibt dort  in NAV 4 Komponenten mit der Position ‚0‘.

![NAV-BOM-POS_0](https://user-images.githubusercontent.com/36193155/125273148-e968bc00-e30c-11eb-8050-5362da19ed06.png)

Wenn ich dann den BOM Dialog nochmal öffne und den „Check“-Button wähle bekomme ich folgendes Ergebnis:
Vier Komponenten haben keine Position und werden als vorhanden gekennzeichnet. Die gleichen Artikel werden unten aber nochmal gelistet, dass sie entfernt werden müssten. Bei diesen ist die Position ‚0‘.
Zudem ist mir aufgefallen, dass dort beim Name keine Dateiextension gelistet ist.

![BOM-Transfer-POS_0](https://user-images.githubusercontent.com/36193155/125273328-1a48f100-e30d-11eb-8327-167011969ce6.png)

Wenn ich dann den BOM Transfer anstoße werden diese 4 Positionen aus der NAV BOM gelöscht. Es fehlen dann also die 4 Komponenten mit Position ‚0‘.

**Comment by PatrickGrub** [comment]
@MarkusCool 
Welchen Wert hatten diese 4 Positionen in Vault vor dem Transfer nach Navision im Feld `Position`?
Leere Positionen sollten eigentlich vermiden werden von dem Template zu Übergabe.

Was möchtest du erreichen und warum?

**Comment by PatrickGrub** [comment]
In Meeting mit Markus konnten wir das lösen:
+ Die genannte Baugruppe hatte für alle BomRows eigentlich Positionsnummern, aber im BOM Window waren einzelne Rows ohne Position
+ Nach einem rekursiven auschecken im Inventor der Baugruppe und anschließenden einchecken hat es im BOM Window die alle BomRows mit den korrekten Positionen angezeigt.
  + Das hat die Situation gelöst!
