### ISSUE TITLE
Inventor Vault-addin Login Error Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by xdumont** [coolOrangeLabs/powerGateTemplate#191]
With VDS add-in activated in Inventor and powerGateTempate in place, when the vault login start, a message appear:
"Object reference not set to an instance of an object."
![image](https://user-images.githubusercontent.com/14092929/132532128-8741cddd-6e21-41df-9f26-e376c1cb4ef0.png)

I fix it by removing "Import-Module powerVault" from the line 1 of  C:\ProgramData\coolOrange\powerGate\Modules\Communication.psm1

![image](https://user-images.githubusercontent.com/14092929/132532199-a1325fbf-8edd-4eda-996e-a5bca0a35328.png)

**Comment by StefanNairz** [comment]
I tried to reproduce the issue on a clean virtual machine with the latest version (`21.0.0.199`) of `powerGateTemplate`.
I had no issues with my testing.
If there are still the same issues for someone, feel free to reopen the issue with a few more details how to reproduce the issue.
