### ISSUE TITLE
Inventor VDS Link ERP Item don't work

### ISSUE THREAD

**Issue by xdumont** [coolOrangeLabs/powerGateTemplate#193]
In Inventor VDS UI, after I save my part and click "ERP Item..." I get a new window.
But it seem this windows is empty, I can't create item or I can't link ERP Item.

![image](https://user-images.githubusercontent.com/14092929/132535881-4ca8a6a3-517c-4635-9cb9-b07cfe4a9bea.png)

PS: My code is fixed with the workarround I explain under issue #191 and #192

**Comment by StefanNairz** [comment]
I tried to reproduce the issue on a clean virtual machine with the latest version (`21.0.0.199`) of `powerGateTemplate`.
I had no issues with my testing.
If there are still the same issues for someone, feel free to reopen the issue with a few more details how to reproduce the issue.
