### ISSUE TITLE
Insert CopyRight information in top of PowerShell scripts

### ISSUE THREAD

**Issue by PatrickGrub** [coolOrangeLabs/powerGateTemplate#195]
Insert CopyRight information in top of PowerShell scripts:
+ Copyright (for legal purposes)
+ Buildnumber (to prove the version)
+ Build time

Copy right example:

```PowerShell
#=============================================================================#
# PowerShell script sample for coolOrange powerEvents                         #
# Restricts the state to release, if the validation for some properties fails.#
#                                                                             #
# Copyright (c) coolOrange s.r.l. - All rights reserved.                      #
#=============================================================================#

```

## One single "AS IS" file in the delivery for legal purposes:

```PowerShell
#=============================================================================#
# Copyright (c) coolOrange s.r.l. - All rights reserved.                      #
#                                                                             #
# THIS SCRIPT/CODE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER   #
# EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES #
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.  #
#=============================================================================#

```

Automate example:
https://github.com/coolOrangeProjects/Outotec/blob/master/SetDateAndVersionInPSFiles.ps1

**Comment by JakobBertagnolli** [comment]
The implementation of inserting copyright information at the top of PowerShell scripts has a negative consequence: the code on GitHub and the code on the customer's machine do not match anymore, making it difficult to refer to specific line numbers when communicating with the customer.

**Comment by JakobBertagnolli** [comment]
> The implementation of inserting copyright information at the top of PowerShell scripts has a negative consequence: the code on GitHub and the code on the customer's machine do not match anymore, making it difficult to refer to specific line numbers when communicating with the customer.

Because of that, we decided to insert the CopyRight information at the **bottom** of powerShell scripts

**Comment by JakobBertagnolli** [comment]
To automate the whole thing even more, it was suggested to check whether the CopyRight information at the bottom already exists. 
If NO then add it, if YES then just replace version and build number.

**Comment by TollJulian** [comment]
> To automate the whole thing even more, it was suggested to check whether the CopyRight information at the bottom already exists.
> If NO then add it, if YES then just replace version and build number.

DONE.
I also changed the major build number to 24, since the code is made for PG 2024
