### ISSUE TITLE
Connect to Live ERP and Test system depending on connected Vault

### ISSUE THREAD

**Issue by PatrickGrub** [coolOrangeLabs/powerGateTemplate#198]
### User story

As a Vault user, I want to be login automatically to my ERP Test system when i log in to my test vault, but when I log in to my productive vault  I want to automatically logged-into my productive ERP system.

### Solution

The solution was already implemented but must be included in our powerGateTemplate:
+  Ensure that in powerJobs no message boxes appear
+ Related to #156
+ See code: https://github.com/coolOrangeProjects/Hauer/blob/1fca6473760ccb3e9b0bbcdaa39aaf2a00d6b0ac/Files/powerGate/Modules/Communication.psm1#L6-L48

**Comment by TollJulian** [comment]
The Vault- and ERP names can be configured as "Test" or "Productive" directly in the Comunication.psm1.
The script selects then the ERP system related to the connected Vault. If the Vault is not mapped, you get an Error message.

Pull Request open

**Comment by TollJulian** [comment]
Implementation tested successfully
+ Vault Client:

https://user-images.githubusercontent.com/95631077/155291223-f24e76b4-0dc1-4aa0-be16-0a92c13f9e34.mp4

+ Inventor:

https://user-images.githubusercontent.com/95631077/155291270-90649a83-b837-44b8-afa2-f2119c18fc62.mp4

**Comment by PatrickGrub** [comment]
Closed see https://github.com/coolOrangeLabs/powerGateTemplate/pull/204
