### ISSUE TITLE
BOM dialog to handle virtual components

### ISSUE THREAD

**Issue by christiangessner** [coolOrangeLabs/powerGateTemplate#20]
If a BOM is created from within Inventor and it includes a VC, the BOM dialog can handle the VC.
It doesn't recognize that it's a VC and shows ERP and Vault has different props. When transferring the items, it overrides the ERP properties with empty values

**Comment by PatrickGrub** [comment]
Fixed in fa7ed8756198572e0d6e2bbce421c91c0bb4addd
