### ISSUE TITLE
Number is empty error message when searching in an empty database

### ISSUE THREAD

**Issue by christiangessner** [coolOrangeLabs/powerGateTemplate#21]
![image](https://user-images.githubusercontent.com/5640189/75431618-616b5780-594d-11ea-809b-36a4fbae7bf4.png)

**Comment by tonionf** [comment]
Issue description is wrong, the error message appears when searching in Number with an incomplete Number in the Inventor Data Standard Search ERP tab. Database not empty.

**Comment by PatrickGrub** [comment]
@HannesDosser 
Wenn du es noch mit der neuesten Version reproduzieren kannst.

**Comment by HannesDosser** [comment]
nicht reproduzierbar
