### ISSUE TITLE
in Powerjobs, ConnectToERPServer doesn't work

### ISSUE THREAD

**Issue by TollJulian** [coolOrangeLabs/powerGateTemplate#215]
Since issue #198 has been resolved, ConnectToERPServer needs the ERP Server Plugin URL as parameter (because the URL isn't unique anymore, but depends on the connected Vault)

In Powerjobs there is still used ConnectToERPServer without any parameter, so a ERP connection can never be established in the jobs

**Comment by TollJulian** [comment]
There is already a function *ConnectToErpServerWithMessageBox* which needs no parameter and connects automatically to the configured ERP system. But this function requires user interaction, since it produces Messageboxes. Not to use e.g. for jobs

I would add a new function *ConnectToConfiguredErpServer* which behaves similar as *ConnectToErpServerWithMessageBox*, but without Messageboxes.

**Comment by TollJulian** [comment]
solution built in into the pull request above

**Comment by PatrickGrub** [comment]
fixed in https://github.com/coolOrangeLabs/powerGateTemplate/pull/216
