### ISSUE TITLE
Use Inventor Project File for powerJobs jobs to prevent out-of-date neutral documents to be exported

### ISSUE THREAD

**Issue by PatrickGrub** [coolOrangeLabs/powerGateTemplate#220]
Use Inventor Project File for powerJobs jobs to prevent out-of-date neutral documents to be exported!

See the problem and solution in Stackoverflow:
+ https://stackoverflow.com/c/coolorange/questions/199/200

**Comment by StefanNairz** [comment]
I've extended & tested both sample Jobs which are located in: `Files/powerJobs/Jobs/` with the code Patrick prepared in stackoverflow like mentioned above.
