### ISSUE TITLE
Property mapping different for Vault and CAD

### ISSUE THREAD

**Issue by christiangessner** [coolOrangeLabs/powerGateTemplate#23]
When in Inventor, a property is mapped and filled, it gets set to an iProperty as well as to the ERP property. When in Vault, it DOESN'T update the UDP but only the ERP property.

This different behavior is confusing for the user

**Comment by christiangessner** [comment]
fixed in the next build due to new architecture

**Comment by PatrickGrub** [comment]
Fixed in fa7ed8756198572e0d6e2bbce421c91c0bb4addd
