### ISSUE TITLE
Search "Number" different in CAD and Vault and not working properly

### ISSUE THREAD

**Issue by christiangessner** [coolOrangeLabs/powerGateTemplate#24]
In Inventor, searching a number with wildcard doesn't work and exposes an error message, in Vault, it doesn't work either but only shows an empty result-grid

![image](https://user-images.githubusercontent.com/5640189/75437937-50274880-5957-11ea-8cb5-f8c57a074fb9.png)

**Comment by PatrickGrub** [comment]
Fixed in fa7ed8756198572e0d6e2bbce421c91c0bb4addd
