### ISSUE TITLE
Vault Items property mapping

### ISSUE THREAD

**Issue by tonionf** [coolOrangeLabs/powerGateTemplate#25]
There is no property mapping between Vault Items and ERP Items

![image](https://user-images.githubusercontent.com/22886425/75471216-348d6380-5992-11ea-8778-2513917657c3.png)

**Comment by christiangessner** [comment]
This has been fixed due to architectural changes. Mapping is now done in the PS1 files and thus can be customized to support files and items. The current version of the template already supports this
