### ISSUE TITLE
Vault Item number changes when creating an ERP item

### ISSUE THREAD

**Issue by tonionf** [coolOrangeLabs/powerGateTemplate#26]
The Vault  Item Number will change to the next available standard number in the system when the ERP Item is created.

![image](https://user-images.githubusercontent.com/22886425/75471489-9f3e9f00-5992-11ea-9a4c-eca1042d6108.png)

**Comment by christiangessner** [comment]
When changing the mapping in the XML file from _PartNumber to _Number, this can be solved. However, due to its architecture, the template is not able to handle both, files and items, at the same time.

**Comment by christiangessner** [comment]
changed the architecture to avoid this problem. will be fixed in next build
