### ISSUE TITLE
Create Wiki documentation powerGateTemplate repo

### ISSUE THREAD

**Issue by christiangessner** [coolOrangeLabs/powerGateTemplate#33]
Readme.md
- [ ] how to install
- [ ] how to modify
- [ ] how to use

Wiki
 - [x] research how to have the documentation in `wiki`-tab as well as in the source code as a folder
 - [x] lanugage for wiki: en, keep de
  - [x] where to put de? remove completely?
- [x] Wiki is only in one language, what about the issues? because i see they can have label DE or EN
- [x] kurz beschrieben wie script (powershell extensions) und wie nutzen

**Comment by lustricker** [comment]
Do you intend this wiki here: 
![image](https://user-images.githubusercontent.com/56259521/76977110-2a2d0c80-6935-11ea-9949-85c253a85455.png)
This issue was fixed here: #66 

Or do you intend a wiki, in which a description on how to use **this** template?

**Comment by christiangessner** [comment]
example for a "home" readme.md: https://github.com/Autodesk-Forge/forge-bucketsmanager-desktop

**Comment by christiangessner** [comment]
already added a frame for this documentation: https://github.com/coolOrangeLabs/powerGateTemplate/blob/master/README.md
needs to be completed with "how to install/configure/use"
