### ISSUE TITLE
Create powerGate Client feature list

### ISSUE THREAD

**Issue by christiangessner** [coolOrangeLabs/powerGateTemplate#34]
Create a list that lists all features of the powerGate client in this repo

**Comment by christiangessner** [comment]
https://teams.microsoft.com/l/file/032A6B76-1887-41A6-B207-F51605A0BCD3?tenantId=2f975c6c-1264-471f-a313-47c70f0f58e4&fileType=docx&objectUrl=https%3A%2F%2Fcoolorange.sharepoint.com%2Fsites%2FSales453%2FDocumenti%20condivisi%2FGeneral%2Fsales%20tools%2FCONNECT%2FpowerGate%2FpowerGate%20Template%20capabilities.docx&baseUrl=https%3A%2F%2Fcoolorange.sharepoint.com%2Fsites%2FSales453&serviceName=teams&threadId=19:e84167e8cfef4f1caccbed59ee070905@thread.skype&groupId=cd3da145-84bc-4f90-b175-f93b09924c19

**Comment by christiangessner** [comment]
include in readme.md? will also be available on the PKB

**Comment by PatrickGrub** [comment]
The current wiki under "Workstation" is documenting the whole client workflow: https://github.com/coolOrangeLabs/powerGateTemplate/blob/master/wiki/_sidebar.md
