### ISSUE TITLE
powerEvents to validate the ERP BOM on release

### ISSUE THREAD

**Issue by christiangessner** [coolOrangeLabs/powerGateTemplate#35]
Bei der Freigabe soll die BOM „validiert“ werden. Im Moment wird über powerEvents der Artikel „validiert“. Das sollte im Template mit aufgenommen werden, da es ein recht übliches und gut angesehenes Feature ist

**Comment by christiangessner** [comment]
check if the BOM exists in ERP and if it's identical with the Vault file/item BOM (same as BOM window would check)
block the state transition if it's not identical

**Comment by PatrickGrub** [comment]
This was already implemented in a project recently by @HannesDosser you can find all information and the code related to [this Github Issue(https://github.com/coolOrangeProjects/Sollich/issues/210):

**Comment by manfredmalleier** [comment]
Issue was implemented.
However, I recommend to refactor some functions (for instance GetEntityNumber) from _powerGateMain.ps1_ to a module used by both powerEvents and powerGate. Currently _powerGateMain.ps1_ is included directly in _powerEvents/modules/Import.Modules.psm1_ to be used in powerEvents.

**Comment by PatrickGrub** [comment]
Mentioned recommended refactor (see above) needs to be done for closing this issue

**Comment by christiangessner** [comment]
Refactoring complete: b99494f
