### ISSUE TITLE
Create an ERP UI Application

### ISSUE THREAD

**Issue by christiangessner** [coolOrangeLabs/powerGateTemplate#37]
In order to demo powerGate, an App would be helpful that displays the ERP data. It needs to be capable of showing, editing and deleting the entities Material, BOM (header and rows) and documents.

**Comment by PatrickGrub** [comment]
It exists a plugin to show the ERP Data in the browser:
https://www.coolorange.com/wiki/doku.php?id=powergateserver:plugins:plugin_gallery:erpview

Maybe this can be extended also to change the values.

**Comment by christiangessner** [comment]
According to Marco, demos with a real ERP are preferable (Navision)

**Comment by christiangessner** [comment]
The database file can be edited by using a free 3rd party app: https://github.com/JosefNemec/LiteDbExplorer/
