### ISSUE TITLE
powerGateModules directory double?

### ISSUE THREAD

**Issue by lustricker** [coolOrangeLabs/powerGateTemplate#39]
Why is there a powerGateModules directory in the `powerGatePlugin` dir with the same content as in `Datastandard` dir?
 
![image](https://user-images.githubusercontent.com/56259521/76630378-333a6a00-6540-11ea-829a-dbbe22e46a62.png)

**Comment by christiangessner** [comment]
@lustricker, can you change the setup to harvest the files from the ErpServices.VDS folder? Actually we would need the folders CAD.Custom, Vault.Custom and powerGateModules.

The reason for having this redundant is that there is a bug in VS that makes it impossible to modify XAML files if they are linked. In the post-build action of the VS project, the files from the project will be copied to the DataStandard directory

**Comment by christiangessner** [comment]
@lustricker, never mind, I fixed this anyways.
