### ISSUE TITLE
Better error message when the Vault Option "powerGateConfig" is not set

### ISSUE THREAD

**Issue by PatrickGrub** [coolOrangeLabs/powerGateTemplate#4]
After installing the template and calling the Vault tabs it throws an error something like "Select-Xml.. not $null parameter".
The source of this problem is that in the current Vault exists no Vault Option called "powerGateConfig".
The template should bring a better error message like "The Vault Option 'powerGateConfig' does not exist, please import it by the function in Vault. GoTo 'Tools->powerGate->Edit' and afterwards 'Save'".

**Comment by christiangessner** [comment]
![image](https://user-images.githubusercontent.com/5640189/75424825-c325c480-5941-11ea-8b73-c590187565f7.png)

**Comment by christiangessner** [comment]
Most likely this is not an issue anymore when #44 is implemented

**Comment by christiangessner** [comment]
Closed with issue #44
