### ISSUE TITLE
Installers: inconsistent names

### ISSUE THREAD

**Issue by christiangessner** [coolOrangeLabs/powerGateTemplate#45]
![image](https://user-images.githubusercontent.com/5640189/76682302-3e9e9b80-65fb-11ea-97a6-c8e754557b64.png)

- [x] The installed jobs should read:  "coolOrange ErpService powerJobs Jobs"
- [x] The installed plugin should read: "coolOrange ErpService powerGate Plugin"
- [x] The VDS extensions should read: "coolOrange ErpService VDS Client"

- [x]  Also, the MSI files should have consistent names...
![image](https://user-images.githubusercontent.com/5640189/76682365-e1571a00-65fb-11ea-821c-68d7ad02b133.png)

**Comment by lustricker** [comment]
Also Todo: 
https://github.com/coolOrangeLabs/powerGateTemplate/issues/13#issuecomment-598911144
