### ISSUE TITLE
PDF creation on Release only works with files but not on Vault Items Release

### ISSUE THREAD

**Issue by tonionf** [coolOrangeLabs/powerGateTemplate#61]
PDF creation on Release only works with files but not on Vault Items Release.
Customer that will use Vault Items will not have this functionality.
To be added also for Demo purpose

**Comment by christiangessner** [comment]
collect all drawings attached to the item
for each drawing, create a PDF
attach the created PDFs to the item

**Comment by TollJulian** [comment]
prepared job and event (branch 'issue_#61')

current problems: 
+ Update-VaultItem is working for unlocked items, but not for locked items
+ couldn't test powerGate transactions yet because no connection could be established on my environment

**Comment by TollJulian** [comment]
I have created issue #215 for the mentioned connection problem. Supposed solution realized in branch issue_#61, created one single pull request for both #61 and #215

**Comment by PatrickGrub** [comment]
fixed in https://github.com/coolOrangeLabs/powerGateTemplate/pull/216
