### ISSUE TITLE
powerEvents would prevent user to release if no ERP Item is associated to BOM files only

### ISSUE THREAD

**Issue by tonionf** [coolOrangeLabs/powerGateTemplate#62]
powerEvents would prevent user to release an assembly if no ERP Item is associated to BOM listed files only and not for any design related file that has no ERP Item.
Currently the system prevents assembly to release also if a design related file like skeleton or parent of a derived part etc.. has no ERP Item.
This is incorrect, the design only related files will not be included in the Inventor BOM and neither in the ERP BOM, no ERP Item is necessary for them.
The system currently takes in account all the files involved in the Vault Release process.

**Comment by christiangessner** [comment]
for demo purposes, a filter on the file extension should be fine, for productive use, the category of the entity should  be used
