### ISSUE TITLE
PDF job to sync properties before creating the PDF

### ISSUE THREAD

**Issue by christiangessner** [coolOrangeLabs/powerGateTemplate#68]
update props before PDF creation

**Comment by PatrickGrub** [comment]
@georgschwienbacher can you remember what was the latest decision on our last discussion about this?

**Comment by georgschwienbacher** [comment]
as discussed in the meeting: the standard Autodesk Sync Job must be used/run before the PDF creation

**Comment by PatrickGrub** [comment]
In order to close this issue we need:
+ Remove in the code the manual Sync (if it's present)
+ Extend the WIKI for the PDF Job

**Comment by TollJulian** [comment]
implemented in pull request #213
