### ISSUE TITLE
Message if no item selected in the search list and user hit OK button

### ISSUE THREAD

**Issue by tonionf** [coolOrangeLabs/powerGateTemplate#88]
Message if no item selected in the search list and user hit OK button. Currently nothing happens and simple user will be trow out of the dialog box.
We add a code to this issue to be added to the product.

**Comment by christiangessner** [comment]
function CloseErpSearchWindow {
    $material = $searchWindow.FindName("SearchResults").SelectedItem
    if ($material) {
        $searchWindow.DialogResult = "OK"
        $searchWindow.Close()        
    } else {
        Show-MessageBox -message "An item needs to be selected to proceed!" -icon "Hand"
    }
}

**Comment by tonionf** [comment]
In  C:\ProgramData\coolOrange\powerGate\Modules\SearchFunctions.psm1  modify the function
"CloseErpSearchWindow" with the following one:
function CloseErpSearchWindow {
    $itemSelected=$searchWindow.FindName("SearchResults").SelectedItem
    if ($itemSelected -eq $nul) {
        [System.Windows.Forms.MessageBox]::Show("Please select an ERP item", "ERP Search Windows", "OK", "Warning")       
    } else {
        $searchWindow.DialogResult = "OK"
        $searchWindow.Close()         
    }

**Comment by tonionf** [comment]
Ok, I see you already did  it...
